import type { Metadata } from 'next'
import './globals.css'
import { fontBody, fontHeadings } from '@/fonts'
import { MainHeader } from '@/components/header/MainHeader'
import { ViewTransitions } from 'next-view-transitions'
import { MainFooter } from '@/components/footer/main-footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ViewTransitions>
      <html lang='es'>
        <body
          className={`${fontHeadings.variable} ${fontBody.variable} antialiased `}
        >
          <MainHeader />
          <main>{children}</main>
          <MainFooter />
        </body>
      </html>
    </ViewTransitions>
  )
}
