import type { Metadata } from 'next'
import './globals.css'
import { fontBody, fontHeadings } from '@/fonts'
import { MainHeader } from '@/components/header/MainHeader'
import { ViewTransitions } from 'next-view-transitions'
import { MainFooter } from '@/components/footer/MainFooter'
import { ScrollLayout } from '@/layouts/ScrollLayout'
import { ScrollTop } from '@/components/ScrollTop'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ViewTransitions>
      <html lang='es'>
        <ScrollTop />
        <body
          className={`${fontHeadings.variable} ${fontBody.variable} antialiased `}
        >
          <ScrollLayout>
            <MainHeader />
            <main>{children}</main>
            <MainFooter />
          </ScrollLayout>
        </body>
      </html>
    </ViewTransitions>
  )
}
